[이수연] 2024 GDG Spring Novice Study - 1주차
dsc-sookmyung/2024-02-Spring-Novice-Study pull request #1
Opened 2024-09-29 14:20 UTC by choubung

1주차 블로그 담당자라서 배운 내용은 GDG 티스토리 글로 갈음하겠습니다. (링크는 따로 첨부하지 않겠습니다.)

개발은 항상 코드 작성보다 환경 설정이 더 힘든 것 같아요🤣
바쁜 일정으로 인해 추가 레퍼런스를 공부하지 못한 채로 과제를 제출하는 게 아쉬워서 시간이 된다면 화요일에 추가적으로 공부해 개인 블로그 글을 작성하려고 합니다. 또.. 독자가 어느 정도 백엔드에 대해 이해하고 있다는 걸 전제로 교재가 쓰여진 것 같습니다. 백엔드 개념은 얼핏만 알고 있어서 추가 공부를 많이 해야할 것 같아요... 열심히 해보겠습니다!

2024-09-30 12:09 UTC, bigtr3 commented on 이수연/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/Main.java
이 코드는 책에 안 나와있는 걸로 아는데 필요한 코드인지 궁금합니다!

2024-09-30 12:10 UTC, bigtr3 commented on 이수연/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/HelloControllerTest.java
> +    public void helloIsReturned() throws Exception {
한글로 메소드를 정의하면 오류가 나서 영어로 하신건가요?

2024-09-30 12:22 UTC, bigtr3 commented on 이수연/freelec-springboot2-webservice/build.gradle
> +    testImplementation('org.springframework.boot:spring-boot-starter-test')
dependencies에 annotationProcessor ('org.projectlombok:lombok')
노션 참고하셔서 추가해주세요

2024-09-30 12:53 UTC, bigtr3 requested changes
정말 수고 많으셨습니다! 수정 사항들 확인해보시고 
수정하셨을때 테스트 실패하시면 답글, 
성공하시면 수정 커밋 날려주세요!

2024-09-30 12:55 UTC, bigtr3 approved these changes

2024-10-01 03:08 UTC, choubung commented on 이수연/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/HelloControllerTest.java
> +    public void helloIsReturned() throws Exception {
처음에 오류 원인을 찾지 못했을 때 혹시나 해서 영어로 바꿔 놨다가 다시 한글로 바꾸는 걸 까먹었습니다... 한글로 고쳐서 다시 올릴까요?

2024-10-01 03:15 UTC, choubung commented on 이수연/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/Main.java
책에 안 나온 코드는 main.java 말씀하시는 걸까요? 제가 만든 건 아니고 프로젝트 생성할 때 같이 만들어졌는데 따로 지우지 않았습니다! 지울까요?

2024-10-01 03:20 UTC, bigtr3 commented on 이수연/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/Main.java
넵 지우시고 테스트 오류나시면 답글 달아주시고, 정상적으로 동작하면 커밋 날려주세요!

2024-10-01 03:20 UTC, bigtr3 commented on 이수연/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/HelloControllerTest.java
> +    public void helloIsReturned() throws Exception {
넵 그게 좋을 거 같습니다!😊

2024-10-01 03:34 UTC, choubung commented on 이수연/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/Main.java
말씀해주신 수정사항들 (dependency 추가, main.java 삭제, 함수명 변경) 반영해 새로 커밋 날렸습니다!

2024-10-01 06:03 UTC, bigtr3 commented on 이수연/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/Main.java
넵 확인했습니다! 수고하셨어요😊

2024-10-01 06:04 UTC, merged