[이경은] 2024 GDG Spring Novice Study - 2주차
dsc-sookmyung/2024-02-Spring-Novice-Study pull request #11
Opened 2024-10-06 15:13 UTC by ruddmslee

## 📒 개요

Ch03 - 스프링 부트에서 데이터 베이스 다뤄보자
- JPA = 자바 표준 ORM
- 프로젝트에 Spring Data JPA 적용해보고 테스트 코드 작성하기
- 등록/수정/조회 API 만들기
- JPA Auditing으로 생성/수정시간 자동화하기

## 👀 새롭게 배운 점
배운 내용과 인터넷을 통해 보충한 내용 정리한 노션 링크입니다!
https://ebony-cap-5f8.notion.site/2-3-11628073f7e280dbb621f179270fb655?pvs=4

## 📍 추가적인 질문
지난주와 관련된 내용이지만 지난 시간에 못 여쭤봐서 여쭤봅니다! 저는 Ultimate 버전을 사용하고 있고 Spring Initializr 플러그인이 설치되어있음에도 지난주 과제 설명 노션에 있는 사진처럼 Generator 부분에 Spring Initializr가 뜨지 않습니다. 구글링해봐도 설치하는 방법만 나와서 해당 부분이 해결되지 않았습니다.. 그래서 웹사이트에서 다운을 받아보다가 궁금한 점이 생겼는데, 웹사이트에서 다운을 받게 되면 혹시 매번 프로젝트를 생성할 때마다 다운을 받아야하는 건가요?? 그리고 Ultimate에서 Generator 부분에 Spring Initializr가 뜨게 하려면 어떻게 하면 좋을지 조언 부탁드립니다! 

## 😄 느낀 점
처음에 책에 있는 코드를 따라서 작성해볼 때는 각 코드가 무슨 의미인지 이해하지 못했는데, 다시 2장부터 읽어보고 와닿지 않는 설명은 인터넷에 찾아보면서 노션에 정리하다보니까 조금이나마 이해가 가기 시작했습니다. 또 Spring Web 계층 개념이 와닿지 않았었는데 코드 각각의 역할을 생각해보고 레퍼런스를 읽어보면서 조금 이해도가 생긴 것 같습니다. 아직은 코드를 해석하는 데에도 시간이 꽤 걸리지만, 나중에는 제가 직접 설계하고 작성해볼 정도로 성장할 수 있었으면 좋겠습니다.

2024-10-06 15:33 UTC, jiwonniy commented on README.md
> +인텔리제이로 스프링 부트 시작하기, 스프링 부트에서 테스트 코드 작성
경은님! 지난주에 미처 말씀을 못드렸는데 저희 전체 readme를 수정하시면 충돌이 납니다.
그렇기 때문에 이 리드미를 저희 레파지토리에 있는 https://github.com/dsc-sookmyung/2024-02-Spring-Novice-Study 리드미를 원래대로 복사하셔서 커밋 푸시해주세요.

만약 md 파일로 정리를 하고 싶으시다면 경은님 이름 아래 ex) 이경은/폴더명/week01.md 이런 형식으로 정리하시는 걸 추천드릴게요!

2024-10-06 15:33 UTC, jiwonniy commented on 이경은/freelec-springboot2-webservice/build.gradle
> +    implementation('com.h2database:h2')
1주차에 말씀을 못드렸는데, 경은님 폴더 구조를 보면 build.gradle 밖에 존재하지 않습니다.
![폴더구조](https://github.com/user-attachments/assets/ba902ed4-8cea-4b00-b229-17c0f46dec36)

보통의 폴더 구조는 이렇기 때문에
![다른폴더구조](https://github.com/user-attachments/assets/f82231bd-94ba-486b-b38e-c64cb3691a07)

혹시 build.gradle을 제외한 다른 파일들 및 gradle/wrapper 폴더가 있다면 그것도 함께 커밋 푸시 해주세요!
나중에 배포실습을 할 때 깃허브를 통해서 코드를 빌드하기 때문에 해당 파일 및 폴더들이 있는 편이 좋을 것 같아요.

2024-10-06 15:46 UTC, ruddmslee commented on README.md
> +인텔리제이로 스프링 부트 시작하기, 스프링 부트에서 테스트 코드 작성
안녕하세요! 앗 죄송합니다.. README도 써야하는 줄 알았어요 😓  복사해서 푸시했는데 지금은 충돌이 해결된 건가요??! 아직 아래에 'This branch has conflicts that must be resolved' 문구가 떠서요!

2024-10-06 15:55 UTC, jiwonniy reviewed
질문에 대한 답변을 남겨드리자면, 
![이니셜라이저](https://github.com/user-attachments/assets/104cc381-f0bf-4c73-847c-eb52a9dec0b2)
해당 Springboot 항목에 마우스를 가져다 대면 **Spring Initializer 서비스를 사용해서 SpringBoot 애플리케이션 생성**이라고 뜹니다. 플러그인이 설치되어 있으면 SpringBoot를 누르면 SpringInitializer로 생성하는 것과 같은 것 같아요. 서버 URL도 start.spring.io로 되어있고요. 노션과 달리 인텔리제이 UI가 조금 변화한 것 같네요!

저의 경우에는 보통 웹사이트 Spring Initializer를 통해서 프로젝트를 생성하고 다운받고 압축 해제해서 사용하는 편이고 주변에서도 이 경우를 더 많이 봤던 것 같아요!

2024-10-06 16:04 UTC, jiwonniy commented on README.md
> +|6주차| 08장[EC2 서버에 프로젝트를 배포해보자]|이지은|
35번째 빈 줄까지해서 완전 그대로 복붙하셔서 다시 한 번 복사해서 커밋 푸시 부탁드립니다,,!

2024-10-06 16:23 UTC, jiwonniy commented on README.md
> +|6주차| 08장[EC2 서버에 프로젝트를 배포해보자]|이지은|
경은님 혹시 force push 사용하셨을까요,,?

2024-10-06 16:25 UTC, ruddmslee commented on README.md
> +|6주차| 08장[EC2 서버에 프로젝트를 배포해보자]|이지은|
네.. 제가 뭔가 잘못 손댄 것 같아요.. 커밋 기록이 너무 많으면 지저분할까봐 기존 README 복구 푸시 기록을 지우려다가 그 다음꺼인 기타 파일들 푸시한 것까지 삭제가 됐는데 기존에 IDEA의 changes 부분에 66개 파일이 있었는데 푸시기록을 삭제하면 원래 다 돌아와야할텐데 15개밖에 안 돌아왔는데 어떻게 해야하나요.. 인터넷에 찾아보니까 reflog의 해시값을 복사해서 git checkout을 하라던데 이게 맞나요..? 또 함부로 손대면 더 문제가 커질까봐요.. 번거롭게 해드려서 정말 죄송합니다..

2024-10-06 16:40 UTC, jiwonniy commented on 이경은/freelec-springboot2-webservice/build.gradle
> +    implementation('com.h2database:h2')
force push 이후로 이 커밋이 사라진 것 같은데,
gradle/wrapper 폴더와 .gitignore, gradlew, gradlew.bat, settings.gradle 이 3가지 파일
총 4가지 커밋 푸시 해주세요! 만약 커밋 푸시가 안된다면 디코에 연락주시거나 일단 두시면 좋을 것 같습니다,,!

2024-10-07 01:31 UTC, jiwonniy commented on 이경은/freelec-springboot2-webservice/build.gradle
> +    implementation('com.h2database:h2')
build 폴더가 커밋됐던 거로 기억하는데, 보통 **build/**는 gitignore에서 관리되는 폴더이기에 없어도 괜찮을 것 같습니다.

2024-10-07 01:43 UTC, jiwonniy commented on 이경은/freelec-springboot2-webservice/build.gradle
> +    implementation('com.h2database:h2')
이 상태에서 settings.gradle 파일만 추가해주시면 좋을 것 같습니다.

2024-10-07 07:16 UTC, ruddmslee commented on 이경은/freelec-springboot2-webservice/build.gradle
> +    implementation('com.h2database:h2')
앗 혹시 settings.gradle 파일의 경로가 어떻게 되는지 알려주실 수 있으실까요?? 제 프로젝트에 settings.gradle 파일이 없는지 검색해봐도 나오지 않아서요.. 그리고 오늘 다시 IDEA 들어가보니  changes랑 unversioned file 부분에 어제 복구되지 않았던 몇 개의 파일이 돌아와있더라구요..!! 더 복구가 되는지 기다려보고 추후에 추가적으로 푸시하도록 하겠습니다!

2024-10-07 07:28 UTC, ruddmslee commented on 이경은/freelec-springboot2-webservice/build.gradle
> +    implementation('com.h2database:h2')
아무래도 경로를 못 찾는 것보단 파일이 없는 것 같아서 제가 수동으로 생성을 해야할 것 같은데 혹시 어떤 내용이 들어가야 하는지 알려주실 수 있으실까요??

2024-10-07 07:33 UTC, jiwonniy commented on 이경은/freelec-springboot2-webservice/build.gradle
> +    implementation('com.h2database:h2')
settings.gradle 는 사진과 같이 build.gradle과 같은 위치에 있습니다. 단일 프로젝트이기 때문에... 없다면 푸시 안하셔도 됩니다!

그리고 지금 경은님의 폴더구조를 봤을 때 src 파일 아래에 있는 자바 코드 파일들만 있으면 상관없기 때문에
폴더들과 파일들의 구조를 잘 살펴보시고, 필요없는 파일들은 커밋 푸시 안하시는 편이 좋을 것 같습니다~ 

원래는 교재에서와 같이 .gitignore로 올라가지 않아도 되는 파일들을 관리하게 되는데요
나중에 프로젝트를 진행하신다면 .gitignore파일로 깃허브에 올릴 파일들을 관리해보시면 좋을 것 같아요!

2024-10-07 07:36 UTC, ruddmslee commented on 이경은/freelec-springboot2-webservice/build.gradle
> +    implementation('com.h2database:h2')
넵 알겠습니다!! 이번에 제가 많이 번거롭게 해드렸는데 친절하게 답변해주셔서 정말 감사합니다 😄

2024-10-07 07:58 UTC, ruddmslee commented on 이경은/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/domain/posts/PostsRepositoryTest.java
> +package com.jojoldu.book.springboot.web.domain.posts;
푸시했습니다! Compact Middle Packages 옵션 때문에 springboot.web으로 되어있던 걸 springboot까지만 봐서 거기에 생성해버렸네요 😓

2024-10-07 09:44 UTC, jiwonniy requested changes

2024-10-07 09:44 UTC, jiwonniy commented on 이경은/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java
> +import org.graalvm.nativebridge.Idempotent;
제가 실행시켜보니 import org.graalvm.nativebridge.Idempotent; 이것때문에 오류가 나더라구요. (처음 보는 것이라..)
노트북에서 실행시킬 때 필요한 라인이라면 그대로 두시고 사용하지 않는 import문이라면 삭제해주세요!

2024-10-07 09:45 UTC, jiwonniy commented on 이경은/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java
> +import org.graalvm.nativebridge.Idempotent;
제가 실행시켜보니 import org.graalvm.nativebridge.Idempotent; 이것때문에 오류가 나더라구요. (처음 보는 것이라..)
노트북에서 실행시킬 때 필요한 라인이라면 그대로 두시고 사용하지 않는 import문이라면 삭제해주세요!

2024-10-07 09:53 UTC, jiwonniy commented on 이경은/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java
> +import org.graalvm.nativebridge.Idempotent;
더 찾아보니 graalvm-jdk-17를 사용하고 계셔서 import가 된 것 같기도 하네요,,? (+새로운 걸 알아갑니다..)

2024-10-07 12:02 UTC, ruddmslee commented on 이경은/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java
> +import org.graalvm.nativebridge.Idempotent;
앗 그럼 수정할 필요 없는 건가요??!

2024-10-07 12:10 UTC, ruddmslee commented on 이경은/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java
> +import org.graalvm.nativebridge.Idempotent;
해당 줄을 주석처리하고 PostsRepositoryTest랑 PostsApiControllerTest를 실행해봤을 때 오류가 안 나던데 그럼 지우는 게 좋을까요??

2024-10-07 12:25 UTC, jiwonniy commented on 이경은/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java
> +import org.graalvm.nativebridge.Idempotent;
스프링부트 실행이랑 PostsRepositoryTest, PostsApiControllerTest 테스트코드 실행이 잘되면 주석처리하거나 지워도 될 것 같습니다!

2024-10-07 12:41 UTC, ruddmslee commented on 이경은/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java
> +import org.graalvm.nativebridge.Idempotent;
지워서 푸시했습니다!

2024-10-07 12:49 UTC, jiwonniy approved these changes
실행 확인했습니다!
2주차 스터디도 수고하셧습니다!!💖🔥

2024-10-07 12:51 UTC, ruddmslee commented
수고 많으셨습니다 😊🔥

2024-10-08 02:35 UTC, merged